app:
  kafka:
    consumer:
      topic-reply-registrator: ${KAFKA_CONSUMER_TOPIC_REPLY_REGISTRATOR:event-reply-generator-one}
    producer:
      topic-event-generator-one: ${KAFKA_PRODUCER_TOPIC_EVENT_GENERATOR_ONE:event-generator-one}
spring:
  application:
    name: generatorOne
  datasource:
    username: ${USER:root}
    password: ${PASSWORD:root}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${KAFKA_GROUP:generator-one}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: com.example.kafka.BaseDtoSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: ${SERVICE_PORT:8081}